export const APPS = [
  {
    id: 'gestion-manager',
    title: 'Gestion Manager',
    description: 'Console managers, promoteurs, clients, campagnes WhatsApp & email.',
    url: 'https://manager-com.boxingcenter.fr/',
    accent: 'blue',
    tag: 'Admin',
  },
  {
    id: 'gestion-fiche',
    title: 'Fiches IK',
    description: 'Génération des indemnités kilométriques — Guillaume CESSAC.',
    url: 'https://fiche-ik.boxingcenter.fr/',
    accent: 'gold',
    tag: 'IK',
  },
  {
    id: 'compta-boxing',
    title: 'Compta Boxing',
    description: 'Devis & factures clients, factures d\'achat WhatsApp, rapprochement bancaire, export comptable.',
    url: 'https://compta.boxingcenter.fr',
    accent: 'green',
    tag: 'Compta',
  },
  {
    id: 'clients',
    title: 'Clients',
    description: 'Liste des clients Boxing Center — consulter les fiches et envoyer emails / WhatsApp.',
    url: 'https://manager-com.boxingcenter.fr/admin/clients',
    accent: 'violet',
    tag: 'Clients',
  },
  {
    id: 'boxplus',
    title: 'BOXPLUS',
    description: 'Boutique en ligne Boxing Center — abonnements, matériel, inscriptions.',
    url: 'https://boutique.boxingcenter.fr',
    accent: 'red',
    tag: 'Boutique',
  },
  {
    id: 'boxplus-admin',
    title: 'BOXPLUS Admin',
    description: 'Administration boutique — offres, matériel, contrats & commandes.',
    url: 'https://boutique.boxingcenter.fr/admin',
    accent: 'red',
    tag: 'Admin',
  },
];
