export const APPS = [
  {
    id: 'gestion-manager',
    title: 'Gestion Manager',
    description: 'Console managers, promoteurs, clients, campagnes WhatsApp & email.',
    url: 'https://gestion-manager.vercel.app',
    accent: 'blue',
    tag: 'Admin',
  },
  {
    id: 'gestion-fiche',
    title: 'Fiches IK',
    description: 'Génération des indemnités kilométriques — Guillaume CESSAC.',
    url: 'https://gestion-fiche-ik.vercel.app',
    accent: 'gold',
    tag: 'IK',
  },
  {
    id: 'compta-boxing',
    title: 'Compta Boxing',
    description: 'Factures d\'achat WhatsApp, rapprochement bancaire, export comptable — 3 salles.',
    url: 'https://compta-boxing.vercel.app',
    accent: 'green',
    tag: 'Compta',
  },
  {
    id: 'clients',
    title: 'Clients',
    description: 'Liste des clients Boxing Center — consulter les fiches et envoyer emails / WhatsApp.',
    url: 'https://gestion-manager.vercel.app/admin/clients',
    accent: 'violet',
    tag: 'Clients',
  },
  {
    id: 'boxplus',
    title: 'BOXPLUS',
    description: 'Boutique en ligne Boxing Center — abonnements, matériel, inscriptions.',
    url: 'https://box-plus.vercel.app',
    accent: 'red',
    tag: 'Boutique',
  },
];
