export const APPS = [
  {
    id: 'gestion-manager',
    title: 'Gestion Manager',
    description: 'Console managers, promoteurs, clients, campagnes WhatsApp & email.',
    url: 'https://gestion-manager.vercel.app',
    accent: 'blue',
    tag: 'Admin',
  },
  {
    id: 'gestion-fiche',
    title: 'Fiches IK',
    description: 'Génération des indemnités kilométriques — Guillaume CESSAC.',
    url: 'https://gestion-fiche-ik.vercel.app',
    accent: 'gold',
    tag: 'IK',
  },
  {
    id: 'compta-boxing',
    title: 'Compta Boxing',
    description: 'Factures d\'achat WhatsApp, rapprochement bancaire, export comptable — 3 salles.',
    url: 'https://compta-boxing.vercel.app',
    accent: 'green',
    tag: 'Compta',
  },
  {
    id: 'infobox',
    title: 'InfoBox',
    description: 'Collecte de contacts BoxRec — managers, matchmakers, promoteurs.',
    url: 'https://infobox-boxing-center.vercel.app',
    accent: 'violet',
    tag: 'Scraping',
  },
  {
    id: 'boxing-portet',
    title: 'Boxing Portet',
    description: 'Site vitrine & chatbot du club Boxing Center Portet-sur-Garonne.',
    url: 'https://boxingcenterportet.fr',
    accent: 'red',
    tag: 'Site web',
  },
];
